name: Tag a Release
on:
    push:
        branches: [ 'master' ]
jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
            -   uses: 1k-off/action-semver-tag-release@1.0.1
                id: tag
                with:
                    version: latest
                    github_token: ${{ secrets.GITHUB_TOKEN }}